### ISSUE TITLE
bug percorso bloccato

### ISSUE THREAD

**Issue by PsykeDady** [ivochan/WumpusGame#2]
se una roccia viene incontrata sul path, viene notificato ma cmq non viene bloccato l'andamento del personaggio 
Vedere le immagini: 

Prima: 
![image](https://user-images.githubusercontent.com/27916449/108125426-b6493600-70a8-11eb-9633-3a9b0abf7957.png)

Dopo: 
![image](https://user-images.githubusercontent.com/27916449/108125611-fa3c3b00-70a8-11eb-8a90-d07da308512d.png)

**Comment by ivochan** [comment]
controllato negli ultimi test
