### ISSUE TITLE
Al primo posizionamento i sensori non rilevano

### ISSUE THREAD

**Issue by PsykeDady** [ivochan/WumpusGame#4]
al primo posizionamento non vengono rilevati i sensori, ecco le immagini del personaggio che va avanti e poi indietro:

va avanti:
![image](https://user-images.githubusercontent.com/27916449/108126374-0ffe3000-70aa-11eb-8d8a-5f78c54aac44.png)

torna indietro
![image](https://user-images.githubusercontent.com/27916449/108126321-007ee700-70aa-11eb-9f16-5733ed20fb2f.png)

**Comment by PsykeDady** [comment]
ecco la mappa del gioco 
![image](https://user-images.githubusercontent.com/27916449/108126582-4dfb5400-70aa-11eb-8fcf-dfaae6a0583d.png)

**Comment by ivochan** [comment]
risolto...da testare
aggiunta anche  stampa se non ci sono sensori di cui informare l'utente
