### ISSUE TITLE
Legenda errata

### ISSUE THREAD

**Issue by PsykeDady** [ivochan/WumpusGame#6]
La legenda mostra le lettere della mappa completa, inutili per la mappa in "avanscoperta"

**Comment by ivochan** [comment]
aggiornati i metodi di stampa della classe GameMap:
-all'avvio del gioco, per debug, verrà mostrata la mappa completa di tutti gli elementi di gioco, con la relativa legenda, usando il metodo mapAndLegend();
-durante lo svolgimento della sessione di gioco verrà utilizzato il metodo mapToString(), in modo da avere a video la legenda delle celle che verranno scoperte giocando;
