### ISSUE TITLE
Su console non viene vista la vittoria

### ISSUE THREAD

**Issue by PsykeDady** [ivochan/WumpusGame#8]
probabilmente a causa del clear Console

consiglio di aggiustare scrivendo la vittoria dopo il clear console ( oppure sostituire il clearconsole con una serie di stampe così si può scrollare sopra)

**Comment by ivochan** [comment]
bc548180a497af892dbe045a5e0dd887207be9c4

**Comment by ivochan** [comment]
bc548180a497af892dbe045a5e0dd887207be9c4
